### ISSUE TITLE
Using `play(-1)` on complete causing 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by JasonStorey** [maxwellito/vivus#108]
https://jsfiddle.net/b97f469p/

When onComplete animation finishes, there is an unhandled exception.

```
var options = {
    duration: 100, 
    type: 'oneByOne',
    animTimingFunction: Vivus.EASE
};

var vivus = new Vivus('my-svg',	options, onComplete);

function onComplete() {
    // when this finishes, a max call stack exception is thrown
    vivus.play(-1);
}
```

**Comment by maxwellito** [comment]
The error is triggered when the rewind is over. Because the at the end of it it, the callback is called, which will try to rewind the Vivus instance which is already re-winded. So it will call your `onComplete` on loop.

If you want to draw and rewind in loop, I recommend you to look at this issue #83

**Comment by JasonStorey** [comment]
Ah, I see. Makes perfect sense, thank you.
