### ISSUE TITLE
Animating dashed lines?

### ISSUE THREAD

**Issue by mateitudor** [maxwellito/vivus#110]
Hello,
Just wanted to ask if it would be possible to animate dashed lines.

I would appreciate an answer, even though you must get this question all the time.
It also goes without saying that you rock.

Thank you.

**Comment by maxwellito** [comment]
Hallo,
Thanks for these sweets words, even if Vivus is that good due to a all the
contributors and not only one person :)
Unfortunately, I'm sorry to tell you that it's not possible to animate
dashed path with Vivus. This is a rare usecase that I never though about
implementing it. Also because the core of the animation is based on this
property. However, if it's really important for you, it must be possible to
hack the library to do it.
Btw, I think you're the first to ask ;)

**Comment by stevesunderland** [comment]
👍

**Comment by dalisoft** [comment]
+1 maybe second

**Comment by SuperDuperPengu** [comment]
And I may be third. I also need this feature. Was anyone able to implement this? Great library, BTW.

**Comment by skill83** [comment]
+1

**Comment by mardulas** [comment]
+1

**Comment by claud-io** [comment]
+1
