### ISSUE TITLE
Choppy animation in IE Edge

### ISSUE THREAD

**Issue by mateitudor** [maxwellito/vivus#113]
Hello. Any idea why animations look so choppy in IE?

This is the code I have for each of these icons (there are no more than 4 running at any given time):
`  coursesIcon1  = new Vivus('coursesIcon1', {type: 'delayed', animTimingFunction: Vivus.EASE, animTimingFunction: Vivus.EASE_OUT, duration: 100,  start: 'manual',    dashGap: 10, forceRender: true});
`

![vivus-ie](https://cloud.githubusercontent.com/assets/1410849/16360066/55c7768e-3b56-11e6-81c2-5055a1f99c64.gif)

Thank you in advance.

**Comment by maxwellito** [comment]
Hello,
I'm sorry I don;t really what you mean by choppy. From the GIF you're providing the animation looks correct. Except if the timing is identical, in that case, yes, it looks weird. 
Can you set this up into a JSfiddle or send me the link of your page please?
Also which version of IE is that?
Thanks

Btw, you duplicated the `animTimingFunction` attribute in your option object.

**Comment by mateitudor** [comment]
Hey, sorry for the delay, I wasn't in town.
So I took the duplicated animTimingFunction attribute, in fact I took both of them out and simplified everything. Took the dashGap thing out too.

The animation still looks really, really slow on IE compared to any other browser. Any idea why? I appreciate your effort and the fact you answered.

**Comment by maxwellito** [comment]
Well I will need more details :) can you provide me a jsFiddle or link to
your demo? Which versions of IE are laggy? Other browsers are fine?

**Comment by mateitudor** [comment]
Whoa, thank you for the superfast response. This is a quality testing build of the menu where I am using your awesome library: http://qa.baeldung.com (hover over the main menu items to activate the dropdown).

I am using IE Edge through a VM (Windows 10), on a 2015 iMac. The thing is, short of buying a Windows machine there is no way to understand if the animation is laggy due to the VM or the svg support.

I looked in your closed issues and found someone with a similar problem, that is why I asked.
Again, thank you for taking the time out of your day to answer me.

**Comment by garethmorgans** [comment]
Hi there,

Firstly, awesome library. Cheers for all your hard work :)

I am also having this same issue on a Windows Phone - Nokia Lumia 920. However, It works fine in a Microsoft Edge browser on desktop and other mobile and desktop browsers are fine too.

Animations are very, very slow - taking around 4-5 mins to draw in.

Any help would be really appreciated.

**Comment by maxwellito** [comment]
Ok, it took me a while to get my hands on a windows machine. But baeldung
animation are smooth on my machine.
Don't forget that mobile devices got limited resources, and SVG animations
are quite demanding. Also be sure your code don't trigger animations which
aren't visible.
On 6 Jul 2016 11:14 am, "Gareth Morgans" <notifications@github.com> wrote:

Hi there,

Firstly, awesome library. Cheers for all your hard work :)

I am also having this same issue on a Windows Phone - Nokia Lumia 920.
However, It works fine in a Microsoft Edge browser on desktop and other
mobile and desktop browsers are fine too.

Animations are very, very slow - taking around 4-5 mins to draw in.

Any help would be really appreciated.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/maxwellito/vivus/issues/113#issuecomment-230803840>,
or mute
the thread
<https://github.com/notifications/unsubscribe/ABC-EO-CDwj8ix5WyoDSPvkm52ipBnZEks5qS8ZfgaJpZM4I-dvy>
.

**Comment by dbdev** [comment]
Hi,

I've noticed that more than choppy animations on Windows 10 with Microsoft Edge the Vivus SVG animation is causing the SCRIPT70 error blocking completely the javascript runtime.

Here http://www.undsgn.com/uncode/homepages/classic-consultants/ I was forced to add an exception for Vivus for Microsoft Edge otherwise the whole site would stop working.

Does anyone has the same problem?

**Comment by maxwellito** [comment]
The only thing I have in mind is the trick used for IE/Edge. Maybe now Edge
manage SVG in a better way (I have no way to test unfortunately). Is it
possible to try with the option `forceRender: false` and see the result in
Edge (do not try on other browsers)?

**Comment by garethmorgans** [comment]
Thanks for the response - I've given it a try but no luck :(

I thought it might help if you saw it. So, please find a video attached.

Any help is really appreciated.

[IMG_7492.MOV.mov.zip](https://github.com/maxwellito/vivus/files/364082/IMG_7492.MOV.mov.zip)

**Comment by maxwellito** [comment]
There's something very interesting in your video. You can mention the end
of it is displayed at a normal speed. Can you test a blank page with this
animation only? I'm afraid other animations are running simultaneously (or
heavy scripts) and are slowing down the rendering.

**Comment by dbdev** [comment]
Have some of you guys tested to use the SVG as file instead for inline code with Microsoft Edge? Please let me know, I'm struggling with this.

**Comment by garethmorgans** [comment]
I've noticed that as well. No problem - I'll test it with just that animation on the page. I'll send another video when finished.

**Comment by garethmorgans** [comment]
I think youwere right - it's much better on a blank page. I will investigate further and post back on here.

Thanks for your help.

**Comment by dbdev** [comment]
Hi #maxwellito,

did you have by any chance tested my issue? Or should I open another thread?

**Comment by maxwellito** [comment]
Hi @dbdev 
Sorry for the delay I needed a machine with Edge to test your issue. Unfortunately, even by changing the User Agent the animation doesn't display correctly. Some styling issues. However, I think it's a browser/optimization issue. I recorded a profile of your page and it looks like your page is bloated by too much JavaScript to digest, which impact the framerate of the animation rendering.

Here is yours:

![screen shot 2016-07-30 at 10 25 08](https://cloud.githubusercontent.com/assets/1097232/17269463/9f398b86-5640-11e6-9401-86dc63d8429a.png)

We can see the CPU going mad, probably due to other frameworks to load. This impact the animations. Chrome seems to manage it correctly, but Edge is not not as optimised and handle it badly.

Here is the difference with the Vivus demo page:

![screen shot 2016-07-30 at 10 30 01](https://cloud.githubusercontent.com/assets/1097232/17269471/e23aa73a-5640-11e6-8e67-8d8602187817.png)

This is also why now I explicitly ask to sandbox the buggy code into a JSfiddle (or other platform) to analyze it and debug it.

I'm sorry to tell you to think about optimising the loading of your page to avoid overload. This should affect the smoothness of your animations.
