### ISSUE TITLE
Animation for Google Maps Marker

### ISSUE THREAD

**Issue by Pixelous** [maxwellito/vivus#127]
Hi @maxwellito,

can you please take a look if it is possible to enable animation for Google Maps marker?

https://developers.google.com/maps/documentation/javascript/markers

https://developers.google.com/maps/documentation/javascript/examples/marker-animations

Looks it supports SVG. Please see

Symbols
In addition to raster images, a marker supports the display of vector paths called Symbols.

**Comment by maxwellito** [comment]
Hi @Pixelous,
Well if you find a way to provide an SVG to the Google API you can try to use Vivus. However I'm afraid they use an `img` tag to display the SVG, so Vivus will be useless. Because, if I get it right, the only thing you can provide is a path (:`url: 'images/beachflag.png'`).

But if it's the case, you might have a last card to play. It;s to create an SVG which contain a `<style>` tag to animate your picture (like [this logo](https://github.com/lnug/resources/blob/master/animated-logo/lnug_animated_logo.svg), check the rendering and the code).

**Comment by maxwellito** [comment]
**EDIT**: I just realised this solution is not perfect. The SVG doesn't render on Firefox, but does en Chrome. It's maybe due to the base64 encoding.
