### ISSUE TITLE
Path element data gets undefined value

### ISSUE THREAD

**Issue by tiborsaas** [maxwellito/vivus#128]
### Please define your problem or issue as clear as possible.

For a problem, please fill the following:

**Vivus version**:
Latest

**Browser**:
Chrome latest

**Steps to reproduce it**:
Use the attached SVG
[bulb_on_azure.zip](https://github.com/maxwellito/vivus/files/514422/bulb_on_azure.zip)

Hello, I found an interesting problem. The ground line is not getting drawn. It's the first path element and if you ispect it, it'll have a `d="Mundefined` value.

I'd love to use it because I'm building an SVG heavy site and it would be awesome to animate these illustrations.

**Comment by maxwellito** [comment]
Hallo,
Thanks for your issue (and respecting the guidelines :)
I found out why your SVG is crashing. With this library I learn everyday
about SVG, it's amazing. Your first line is a not valid from my Pathformer
requirements, because the `x1` attribute is missing. But by convention,
browsers seems to replace missing position attributes by `0`. I'll patch
this. For now, please add `x1="0"` to your line then it should run smoothly
;-)

**Comment by tiborsaas** [comment]
Thanks for the quick response. 
I'll try it out shortly and report back. It was exported directly from the latest Illustrator CC.
