### ISSUE TITLE
Have SVG be hidden initially?

### ISSUE THREAD

**Issue by hilary-L** [maxwellito/vivus#137]
First off, really like this library - awesome work. Just having a minor issue, and I'm not sure quite how to get around it. I've noticed that the svg i'm animating appears fully drawn initially, then disappears, then animates in. Ideally, I'd like it to be hidden initially and then animate in. I feel like I must be missing something simple...

I created a fiddle that sort of shows what I'm talking about:

https://jsfiddle.net/7971fakx/

(Although in that fiddle it goes quite fast, so the issue is slightly less noticeable....)

**Comment by maxwellito** [comment]
Hiya!
Thanks for the kind words :)
For inline SVGs a glitch can happen because the SVG is displayed between
the page rendering and the code execution that hide it. So the only way is
to hide it by default, then ask Vivus to make it visible once ready. You
can use 'onReady' (cf jsFiddle fork below) or set the visibility to the
element just after creating the Vivus instance.

https://jsfiddle.net/7971fakx/2/

You're not missing anything, you got it right :)
