### ISSUE TITLE
why isn't this 'simple svg' not animating? I believe it has min. reqs e.g. stroke attribute

### ISSUE THREAD

**Issue by pleabargain** [maxwellito/vivus#145]
### Please define your problem or issue as clear as possible.
i reread the instructions " All elements must have a stroke property and cannot be filled."
my svg has only one element and stroke  `path id="path" stroke-linecap="round"`

**Vivus version**:
online
**Browser**:
latest chrome

**Steps to reproduce it**:
uploaded below svg/ no animation

**JSFiddle link (or similar platform)**:

https://jsfiddle.net/pleabargain/yeap454r/

*[note]*
Please have a minimum of politeness. There's unfortunately only me as contributor/maintainor which help on my free time, I'm not the Amazon customer service or your Mom. I don't ask to send me flowers and tell me how amazing Vivus is (that won't make me help you quicker). But please try to do as much as you can before opening an issue: check that no closed issue mention a similar problem, that your script is executed correctly (conflicts, race conditions...).. Thanks :)
Otherwise I will take a delighted pleasure to reply with `RTFM` or `Learn JavaScript you f***** moron``
*[/note]*

**Comment by maxwellito** [comment]
Hi Dennis,

You're quite close :)
By default, the SVG behaviour is to set the `fill` property to `#000` if not set. Also, you will have to provide a `stroke` property which define the color of your border, otherwise the border is not rendered.

So I recommend you to add `fill="none" stroke="#000"` to your path tag.

You can play with the thickness of the border with `stroke-width`.
