### ISSUE TITLE
Support for linked external SVG sprite

### ISSUE THREAD

**Issue by desko27** [maxwellito/vivus#146]
Hi, I recently learned [this technique](https://una.im/svg-icons/) which allows you to build a custom icon system via a linked external SVG sprite.

So the icon of choice is written to the DOM like this:
```html
<svg id="the-icon">
  <use xlink:href="sprite.svg#icon-of-choice"></use>
</svg>
```

The browser displays the right SVG, but it seems like Vivus cannot animate it. I guess this technique differs from what Vivus expect the SVG element to be.

I'm new to the use of SVG files and I don't know if I'm asking for something stupid. If so, I'm really sorry and you can close the issue.

Thanks!

**Comment by maxwellito** [comment]
Hi there,
Don't worry, there's no silly questions :)
And you actually fount the answer by yourself. Vivus cannot manipulate independently the content of each `use` tag. You could manipulate the definition which will update all the `use` tags. That's how it works.

**Comment by desko27** [comment]
Hi, thanks for your reply!

> You could manipulate the definition which will update all the `use` tags.

What do you mean? Could I use Vivus with my existing markup? I can only think of replacing each `use` definition by JavaScript when DOM is ready, in order to make it valid for Vivus. Would that be a solution?

I really appreciate any advice :)

**Comment by maxwellito** [comment]
Sorry for my explanation.

No, from my old experience with `use` and Vivus. You can animate the parent (:`definition` tag) and all the `use` tag will be updated.

```html
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;" id="definitions">
  <symbol viewBox="0 0 128 128" id="the-icon">
    <path d="M111.5,120.5h-96c-4.418,0-8-3.582-8-8V16c0-3.236,1.949-6.153,4.938-7.391c2.991-1.237,6.432-0.554,8.718,1.734l48.5,48.5 c2.288,2.288,2.972,5.729,1.733z"/>
    <path d="M111.5,120.5h-96c-4.418,0-8-3.582-8-8V16c0-3.236,1.949-6.153,4.938-7.391c2.991-1.237,6.432-0.554,8.718,1.734l48.5,48.5 c2.288,2.288,2.972,5.729,1.733z"/>
  </symbol>
</svg>

<svg id="the-icon">
  <use xlink:href="sprite.svg#icon-of-choice"></use>
</svg>
<svg id="the-icon">
  <use xlink:href="sprite.svg#icon-of-choice"></use>
</svg>
```

If you trigger `new Vivus('definitions')`, the definition will get the animation and the use will be both updated at the same time together. You won't be able to manipulate them independently.

However I don't really recommend it, because Vivus will struggle to know when to trigger the animation, because it refer to the position of the definition in the page and not the position of your `use` tags. 

Plus, and I didn't mentioned before, Vivus won't be able to get it from an external file (:`sprite.svg#icon-of-choice`)

Ill try to post a jsfiddle during the day

**Comment by maxwellito** [comment]
Here is the JSfiddle, I put some comments in it.
Don't hesitate to hack it.
https://jsfiddle.net/svhf9jwz/

**Comment by desko27** [comment]
Oh, now I get it! Thank you so much for your clear explanation and the examples, the JSfiddle has been of a tremendous help 😃

Now that I understand how it works I managed to get it working by using [svg4everybody](https://github.com/jonathantneal/svg4everybody) with `polyfill: true` to embed each definition from `sprite.svg` directly into every `use` tag which actually transforms them into independent inline SVGs. This way Vivus can manipulate them separately.

Vivus is awesome, huge thanks for your time!

**Comment by maxwellito** [comment]
You're welcome sir!! :)
