### ISSUE TITLE
Scale svg to fit screen

### ISSUE THREAD

**Issue by peterennis** [maxwellito/vivus#147]
### Please define your problem or issue as clear as possible.

For a problem, please fill the following:

**Vivus version**: 0.4.0

**Browser**: All

**Steps to reproduce it**:
Create animation is Ionic2 using adapted code example:

```
  ionViewWillEnter() {
    console.log("vivae ionViewWillEnter - This function will be called every time you enter the view");
    new Vivus('aeternity', {
     file: 'assets/svg/ae_mousepad_print_vivae.svg',
       onReady: function (Vivus) {
       // `el` property is the SVG element
       Vivus.el.setAttribute('height', 'auto');
      }
    });
  }
```

I would like to auto scale the svg to the screen width/height as appropriate.
The "auto" option does not appear to work as used.
If I hard code a value to the size of the svg
it shows up on iPad and is cut off on phones.

![capture024](https://cloud.githubusercontent.com/assets/140737/23581945/ebb39892-00d3-11e7-8702-4910b4b455fd.png)

**JSFiddle link (or similar platform)**:
*No personal website will be allowed, only sandboxed platform where the code is isolated and can be hacked.*

**Comment by maxwellito** [comment]
Hi there,
By loading it dynamically, the SVG should take the full space provided by the parent container. Can you please provide me the link to your dev page, I'll have a look. :)

**Comment by peterennis** [comment]
It is running as a PWA here: adaept.com
The attachment shows a snip of the animation.It does not appear to have a direct link.
Let me know what else you need if that is not sufficient.
Thanks,
Peter

 

    On Sunday, March 5, 2017 12:40 AM, maxwellito <notifications@github.com> wrote:
 

 Hi there,
By loading it dynamically, the SVG should take the full space provided by the parent container. Can you please provide me the link to your dev page, I'll have a look. :)—

**Comment by maxwellito** [comment]
Hi there,

Ok so I mentioned two things here. 
- Your SVG tag doesn't have a `viewBox` property which is very important. It define the area of your SVG, the browser will use it to resize and display correctly the SVG. For example, on yours I would recommend to set `viewBox="0 0 720 720"`, it should fit. => `<svg viewBox="0 0 720 720" ...`. You can read the [MDN documentation](https://developer.mozilla.org/fr/docs/Web/SVG/Attribute/viewBox) for more info 
- You seems to have used vivus-instant for this SVG and also have the Vivus JS library on your page. I hope you're using only one or the other but not both, otherwise that might ruin performances and have weird behavior :)

**Comment by peterennis** [comment]
Updated to use latest Inkscape and it added the `viewbox`.
I used the Vivus library and a non instant SVG.
It works well.
Thanks for the help.
