### ISSUE TITLE
Make it work in universal environments

### ISSUE THREAD

**Issue by rauchg** [maxwellito/vivus#152]
If you're trying to use `Vivus` in a universal (server-rendered) app, even if the code won't execute on the Server, it will fail to evaluate because it assumes `window` to be there.

https://github.com/maxwellito/vivus/blob/master/src/_build.js#L23

If you make that check optional, it'll be much easier to bundle `Vivus` in apps made with, for example, [Next.js](https://zeit.co/blog/next) etc

**Comment by maxwellito** [comment]
Hi Guillermo,

Thanks for passing by, that wasn't expected :)

So, I understand this issue, and since I put this package to NPM I always felt bad/uncertain about if I was doing this right. And to be fair, you seems like the person of the situation for it.

I know the bundling I have is alright if Vivus is used for Browserify: to end in a browser. But I'm completely confused when it come to serverside rendering for many reasons:

- I don't know how this library could be used on serverside except to render a SVG at a different step of the animation (:like render a SVG at 75% of the animation).
- This library depends a lot on the SVG Element API. The Pathformer class transform graphical elements to path elements, Vivus need to get the length of every path that via the `.getTotalLength()` method.

This is why if I make the `window` object optional Vivus might become useless. Is serverside rendering able to provide me the same API as a browser? Like SVGElement, `getTotalLength()`..

I'm really sorry my points are absolutely silly. I admit I have a bad knowledge of this area.
Thanks again for your issue 👍

**Comment by rauchg** [comment]
Even though it doesn't do anything meaningful on the server, I think it'd still be cool if it also didn't cause an error. I say this strictly from the perspective of complying with existing packaging tools, not that it'd necessarily be "the right way". So, I've used a workaround for now (by loading the lib lazily), but it'd make creating one bundle much easier if it didn't cause an error when `window` is absent.

**Comment by maxwellito** [comment]
Oh ok :)

So, the solution would be to remove the parameters `window` and `document` from self executed function. 

**`_build.js`**:
```js
'use strict';

(function () {

  // bundling logic

}());
```

Am I right?

**Comment by rauchg** [comment]
Correct. I think many libraries do this already, because we're able to bundle them fine even though they're browser-only. For example, a recent one I used in this way is `unfetch`: https://github.com/developit/unfetch

**Comment by maxwellito** [comment]
Ok, tests are good. If this [PR](https://github.com/maxwellito/vivus/pull/153) is good for you, I'll ship it. :)

**Comment by maxwellito** [comment]
Thanks @rauchg for your update. 
Its not merged and publish. 
Can you confirm it's now working? Thanks :)
