### ISSUE TITLE
Vivus silently fails on first page load

### ISSUE THREAD

**Issue by Billybobbonnet** [maxwellito/vivus#156]
When I load my website **without any data from the site in cache**, the vivus animation fails silently (i.e. no console error). Here it is, [live](http://www.elodiedefonte.com).

I use the latest vivus version, and my svg is just a clipath with a single stroke text behind. It occurs in Firefox and Chrome (haven't tested on other browsers yet).

Please let me know if you need more details. Good job on this lib by the way. 👍

**Comment by maxwellito** [comment]
Hi there,
Sorry about the delay, I was away from physical keyboards.
I just checked your page and I don't mention any wrong behavior. The animation starts on scroll. Maybe you fixed the problem since? If you wanted to start the animation on page load without any user interaction I would recommend you to use the option `start: 'autostart'`.

**Comment by Billybobbonnet** [comment]
Hello Max,

It works in most cases. I assumed it was cache related but while testing several times, it happens only like 1/5 times.

I'll give a try with the autostart. Maybe add a little delay (I wrapped in in a document ready event tho) and see if it keeps occurring.

I have to work again on this anyway since I realized that my stylish and beloved clipPath doesn't work with ie/edge (I should have known ^^ ).

Thank you for your answer. If I discover a replicable cause and if it's related to vivus, I'll report that. I will close the issue for now, if it's ok for you.
