### ISSUE TITLE
Animations get laggy when creating 10-20 svg's

### ISSUE THREAD

**Issue by julianorth** [maxwellito/vivus#164]
Hi,
i really enjoy your library. I was playing around with creating 20+ vivus' instances with 20 different medium complex svg's. The Animation of each svg when loading 20 at once is a bit laggy and not that smooth anymore. They also don't start at the same time. Is this behaviour "normal" because of so much calculation is going on from the animations ?
Tested in newest Chrome Version and mobile Safari and vivus v0.4.1.

Greetings

**Comment by maxwellito** [comment]
Hi there,

This behavior is normal. Even one animation on a complex SVG can be quite
demanding in terms of resources. The reason is, at every frame the browser
will rerender the whole SVG. So 20 simultaneous... Im even surprise your
browser is still responding :-D

Also, the reason they don't start all at the same time is due to loading
times. When you create a Vivus instance with lazy load (by using "file:
'my.svg'"), the animation starts when the SVG is loaded. So it's unlikely
that all your SVG get loaded all at the same time.

The only way to control this is to create instances with "start: 'manual'"
and use the callback "onReady" to collect all the ready states. Once
everything is loaded, you can run "play()" on all of your instances.
