### ISSUE TITLE
Dynamic Load Method blocked by CORS

### ISSUE THREAD

**Issue by rfabes21** [maxwellito/vivus#168]
Vivus Version: v0.4.1

Chrome/Firefox: latest

My website is hosted on heroku, it's a Python Django application, static assets are stored on AWS S3, with cloudfront CDN serving them. Initially we only opened the CORS policy to the requesting domain, but we've also tried it with the assets completely available to any GET request:

```
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
</CORSRule>
```

The error is available on the page immediately upon load:

```
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLObjectElement': Blocked a frame with origin "http://xxxxxxxxxxx.com" from accessing a cross-origin frame. at HTMLObjectElement.onLoad (https://cloudfront.com/scripts:1)
```

Haven't been able to set up a JSFiddle yet to reproduce, but I haven't seen any other issues related to this (that weren't being served from a filesystem).

**Comment by maxwellito** [comment]
Hi there,

Sorry about the delay. Im afraid the issue comes from a CORS issue as the
error message mention. But I don't know where to help you with the config,
Im a bit pointless on that part. Does your SVG receive the correct headers
during the request?

I will also check on my side if an attribute on the object tag would help.

Hovever, if you check the previous issue (#167), the hack of fetching
manually the SVG and setting it in the DOM seems to work and byassing these
rules. So I'll try to implement this soon.

**Comment by rfabes21** [comment]
We fixed the issue, we had to actually serve the svg files from our webserver, extrapolated from all the other static assets served from S3. Too much of a CORS/Header nightmare otherwise. Outside that we also used a django plugin called django-inline-svg to embed the svg tag into the page rather than dynamically load it.
