### ISSUE TITLE
SVG + animation not showing in safari

### ISSUE THREAD

**Issue by kaspar-allenbach** [maxwellito/vivus#178]
### SVG + animation not showing in safari

**Vivus version**: 0.4.2

**Browser**: Safari 11.0

**Steps to reproduce it**:
Check my Codepen: https://codepen.io/Sepp/pen/RLqBYE
Staging version: https://meteotest.meteotest-test.ch/ (th svg is applied on the big blue surface)

Okay, so I have this code which works well in FF + Chrome but not in Safari.

- There is no error message
- The svg is drawn but not visible. No css applied since it's a codepen.
- ???

It feels like a obvious mistake but at least in codepen there mustn't be any interference, right?

**Comment by maxwellito** [comment]
Hi there,

Thanks for providing details. So the problem is simple, Safari is not friendly with `use` tags. When a symbol is updated, the render is not applied to the duplicates. 
To bypass this I recommend you to use the option `forceRender`. When set to true it rebuild the nodes at every changes to make sure the browser do the rendering. If you set a value that affect IE/Edge and Safari, it should be good :)

```js
new Vivus('SVGitem', {
    duration: 200,
    forceRender: /^((?!chrome|android).)*(msie|edge|trident|safari)/i.test(window.navigator.userAgent)
});
```
