### ISSUE TITLE
when i import vivus to my component for angular4 project, Console error ' __WEBPACK_IMPORTED_MODULE_1_vivus__.Vivus is not a constructor     at ... ' 

### ISSUE THREAD

**Issue by actingcutecat** [maxwellito/vivus#181]
### Please define your problem or issue as clear as possible.

For a problem, please fill the following:

**Vivus version**: ^0.4.2

**Browser**:chrome

*[note]*
when i import vivus to my component for angular4 project, Console error ' __WEBPACK_IMPORTED_MODULE_1_vivus__.Vivus is not a constructor     at ... ' 

I do not know why.

**Comment by maxwellito** [comment]
Hi there,

So I'm not a pro at Webpack (but I'm improving). Are you sure you need to ask the property `Vivus` of the object returned? Because the module export the class directly, not an object wrapping the class.

Can you try `WEBPACK_IMPORTED_MODULE_1_vivus` instead of `WEBPACK_IMPORTED_MODULE_1_vivus.Vivus`?

Maybe I'm saying something silly :-S
