### ISSUE TITLE
SVG loaded through object tag not animating in Chrome

### ISSUE THREAD

**Issue by WojtekWZ** [maxwellito/vivus#210]
**Vivus version**: v0.4.4

**Browser**: Chrome 70.0.3538.67 

**Steps to reproduce it**: Try to use Vivus with an SVG loaded through object tag.

**JSFiddle link (or similar platform)**:  https://jsfiddle.net/6pux87w0/

Hello,

When trying to use Vivus with svg loaded through an object tag I'm encountering an issue in Chrome. 
The animation doesn't start and there's no error message.

The same svg animates fine in Chrome when copy-pasted directly into html.

Firefox and Edge work fine.

When I compare Vivus objects in different browsers, in Chrome `isReady` is set to false and `el` is null. In Firefox it's true and svg object respectively.

I've included the example svg in the fiddle.

Best regards,
Wojciech

**Comment by maxwellito** [comment]
Hi there,

Thanks for reporting a bug and providing a JSfiddle. However the result
looks the same in Chrome, Firefox and Safari. But I have error messages,
first because Vivus wasn't included in the fiddle, aecond because the
linked SVG file is not existant.
I realised Plunkr is more appropriate for Vivus because it allow us to have
custom files: try it here
http://plnkr.co/edit/LgBin9Heuet2TSFM38TY?p=preview

**Comment by WojtekWZ** [comment]
Hi,

Thanks for your response.

Plunk with the example: https://plnkr.co/edit/28wWBhjYikuZOx93mEJ2?p=preview

It's weird - in plunk it animates ok but when I download the plunk and open it in chome it doesn't animate.
