### ISSUE TITLE
Callback not work (scenario type)

### ISSUE THREAD

**Issue by yarovikov** [maxwellito/vivus#213]
Hi )

When i use scenario type callback is not work

http://jsfiddle.net/sw75mLyr/

**Comment by maxwellito** [comment]
Hi there,
Right, your SVG was 'malformed' in a way. The bottom part saying 'Independant garage" was a monobloc which was running browsers crazy. Let say instead of estimating the line length to 200, this path was estimated to 2500. So it was reaching the end of animation at some point but quite late. You can still check, after few second the callback is called.

Anyway, I cleaned up your SVG, you can play with it now. You can check, each letter is now an independant path.

Enjoy!

http://jsfiddle.net/4kcx9boq/1/
