### ISSUE TITLE
Vivus not working properly with path stroke dash array

### ISSUE THREAD

**Issue by steve231293** [maxwellito/vivus#221]
Hello @maxwellito 
Thank you for making awesome plugin.

I have a question:
is Vivus working with svg path stroke dash array?

It's rendering wrong icon with Vivus.
Please view my codepen to see problem.
[https://codepen.io/steve231293/pen/MNawLB](https://codepen.io/steve231293/pen/MNawLB)

**Vivus version**:
0.4.4
**Browser**:
Chrome - Mac Os

**Comment by maxwellito** [comment]
Hi Steve,

Thanks for the kind words and filling the issue correctly :)
I'm afraid Vivus does not work with storke-dasharray. The library override the property to animate paths. I must admit this point should be clearer in the `readme.md`, because you're not the first to ask https://github.com/maxwellito/vivus/issues/10 😅

**Comment by steve231293** [comment]
Thank for your reply.
