### ISSUE TITLE
Should 'async' actually be 'sync'?

### ISSUE THREAD

**Issue by kad3nce** [maxwellito/vivus#30]
Kudos for the great work! Looking forward to using this in my next project.

Just a little nitpick here. I was confused by the usage of the term **async** to describe the second animation option. In my experience, **async** is a term used to describe things that happen at disparate times—not in a synchronized fashion. I think **sync** (synchronous or synchronized) may be what you're after to describe that effect?

![screen shot 2015-02-26 at 1 20 34 pm](https://cloud.githubusercontent.com/assets/556/6402147/44d372d0-bdba-11e4-8e86-0c15c0709942.png)

![screen shot 2015-02-26 at 1 22 12 pm](https://cloud.githubusercontent.com/assets/556/6402181/82755478-bdba-11e4-978e-38bc8eb12d1b.png)

**Comment by maxwellito** [comment]
Thanks!

Yes, I've seen a comment today on hacker news about my weird naming and I've been thinking of it all day. To be honest I never had a look to the proper definition of the words. The only reason I called it `async` is due to the AJAX principle. The requests are asynchronous, this is why we can perform them without blocking the script execution, they run in parallel.

I wouldn't be surprised to be wrong.

The problem is, I want the API to have a correct naming, but if I do it now it means that it won't be compatible with the previous versions. Except if I jump to the next major version, and that would be too big to jump directly on `v1.0.0` (it's not mature enough). But if I do it, I think I would change all the names, and review the way to use scenario types.
