### ISSUE TITLE
SVG sprite issue?

### ISSUE THREAD

**Issue by selfagency** [maxwellito/vivus#53]
Hi, 

I'm using an SVG sprite (using this method https://css-tricks.com/svg-sprites-use-better-icon-fonts/), which I'm embedding inline. I've included the JS in my header and added this code in my footer:

    new Vivus('heading-also-like', {type: 'delayed', duration: 200, start: 'inViewport'});
    new Vivus('heading-trending', {type: 'delayed', duration: 200, start: 'inViewport'});
    new Vivus('heading-latest', {type: 'delayed', duration: 200, start: 'inViewport'});

Unfortunately, it's not working, and I'm getting the following error:

    Error: Vivus [constructor]: "element" parameter is not valid (or miss the "file" attribute)

Am I doing something wrong or does Vivus not support SVG sprites? If not, could you add support?

Thanks!

**Comment by maxwellito** [comment]
Interesting, to be honest I've never tried.
Can you provide me a copy of your DOM to have a general overview? Or a
JSfiddle :-)

To be honest, I would be happily surprised if Vivus accepts SVG sprites.

2015-05-22 17:02 GMT+01:00 Daniel Sieradski <notifications@github.com>:

**Comment by selfagency** [comment]
You can see my dev project at http://v2.nylon.com/.
I have the Vivus js commented out currently.

**Comment by maxwellito** [comment]
Hi Daniel,
Thanks for the example, it's a very interesting use case.
As I said I never tried to use SVG sprites, so it was the good opportunity.

From what I see, the tag `use` is a simple mirror to the original `symbol` tag. If a change is done to the `symbol`, this will affect all the `use` tag referencing it. But the `use` tag don't own a copy they can change. I tried many different ways without success, I'll have to look at the documentation.

So your idea to give the `symbol` ID to Vivus was right. Unfortunately, there's some checking in the Vivus constructor to only accept SVG elements as input. 

I created a fork of it, quickly patched to allow `symbol` tags, and it works : http://maxwellito.github.io/drafts/vivus-issue-53/

However, I mention some little problems:

- By using `inViewport`, Vivus will check when the SVG element is in the viewport to start the animation. But in our case, it's not doable because the symbol tag is hidden. So there's not way to know if it's the viewport. And even if it was visible, it must be at the same place as where you display the SVG.

- The SVG you try to use, is not appropriate for Vivus. This library is made to animate stroke paths. In your case, there's no stroke paths but only filled paths. Unfortunately, Vivus won't animate them.

**Comment by selfagency** [comment]
Thanks, that's quite helpful.

**Comment by maxwellito** [comment]
You're welcome :-)

Now I'm wondering if it would be useful to implement it into Vivus. The
usage restriction is a bit discouraging. Any ideas about it?

2015-05-27 22:49 GMT+01:00 Daniel Sieradski <notifications@github.com>:

**Comment by selfagency** [comment]
You mean in terms of the inViewport not being able to function with a sprite? I bet you can figure out a way around that with jQuery.

**Comment by maxwellito** [comment]
Yes, but not only. The goal of using a sprite is to reuse the same graphics at many different places on your page. Unfortunately it's not possible to control every instance but only the original one. Making the animation sync between instances. That's really uncool.
