### ISSUE TITLE
SVG font --> animated logo. How do I?

### ISSUE THREAD

**Issue by zfrenchee** [maxwellito/vivus#62]
Given an svg file for a font, I'd like to make a vivus effect such that each letter of my logo (which is in this font) loads in parallel. How would I go about that? Things tried:
I used illustrator to make an SVG of the logo. Not sure this is the right approach (would rather just type out the letters)
Then, loading from a file using the second syntax listed. That caused this error, and the logo loaded all at once, no effect:

     Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLObjectElement':
     Blocked a frame with origin "null" from accessing a frame with origin "null". Protocols, domains, and
     ports must match.

The issue seems to be with chrome. So I loaded chrome without security settings. Now the logo loads all at once without effect, but no error either. 

I tried putting all the svg from the illustrator file into my html. Didn't work either. 

I feel like there's some easy way to do this I'm missing.

**Comment by maxwellito** [comment]
Hi there,
About the first point, Vivus cannot manipulate `<font>` elements. The text must be transformed into `<path>` elements in Illustrator.
And about the second point, the error must be due to the use of the protocol `file://`. This is a normal security check from Chrome, otherwise it could allow any local script to load and read any local content. This is why the `file` option can only be used behind a HTTP server. If you're using a Mac, open the terminal, move to your project folder (where you have the HTML and JS files), then run `python -m SimpleHTTPServer`. This command will create a simple http server on http://localhost:8000/
So if you work on the file `hello.html`, you just need to go to http://localhost:8000/hello.html

Tell me how it goes if you need more help.
Otherwise, it would be helpful to have your code on here (or JSfiddle, CodePen...)

**Comment by zfrenchee** [comment]
I ended up using the font to write the words I wanted in Illustrator, then exported as SVG and messed with that to satisfaction. Just to echo some of the other issues, it would be sweet if fills could be animated as well, not only strokes. Thanks!
