### ISSUE TITLE
Change the direction of the animation

### ISSUE THREAD

**Issue by carmi33** [maxwellito/vivus#66]
Hi! Thank you very much for the js, its great and works perfectly.
I only have a problem, i would like to change the direction of the animation of one of my paths and i dont know how. Its a word, and it should appear from left to right, not like now that appears right to left. Can you help me?
The path is the following:

```
<svg version="1.1" id="can-horizontal" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                     viewBox="677.1 0 1628.9 350" enable-background="new 677.1 0 1628.9 350" onclick="can.reset().play();">
<path fill="none" stroke="#DD5A43" stroke-width="2" stroke-miterlimit="10" d="M2147.8,244.6c-113.3-45.7-286.2,117.6-318.8-8.1
                    c-47.9-184.3,201.1-65.4,9.8,7.3c-103.1,39.2-96.7-134.2-174.7-131.6c-20,0.7-90.6,14.9-108.1-10.3c-8-11.6-5.8-24.3-9.4-40.4
                    c-0.1-0.1-0.2-0.1-0.2,0c1,15.9,3.5,47.4-14.4,58c-19.6,11.6-31.6-1-32.2-10.4c-1.4-21.2,13.8-45.9,33.4-52c0.9-0.3,1.7,1,0.9,1.6
                    c-15.1,10.9-26.1,60.6-44.3,76c-8.8,7.3-24.1,8.4-33-9.6c-24.3-49.1-26.7-111.8-17.3-111.8c18.7,0,29,100.6-13.7,129
                    c-46.4,30.9-71.6-23.9-24-11.4c24.8,6.5,34.4,26.9,24.1,44.2c-5.6,9.3-20.8,14.1-35.1,10.3c-11.7-3.1-20-16.3-12.8-17.9
                    c7.2-1.6,8.2,29.9-3.4,35.4c-20.5,9.8-26.3-39.7-44.8-37.7c-9.1,1-10.6,12.3-10.9,19c-0.7,15,2.5,30.4,8.1,44.2
                    c0.1,9.6-27.2-73.1-46.8-108.6c-23.3-42.4-1.3-56.5,13.4-9.5c6.9,21.9,12.4,58.5,11.6,93.6c-1.9,88.4-296.1,35.3-452.2,59.1
                    c-152,23.1-1.5,131.1,7.3,8.1c1.8-25.6-14-59.3-51.2-100.8"/>
</svg>
```
And the script

```
	function easeOutBounce (x) {
		var base = -Math.cos(x * (0.5 * Math.PI)) + 1;
		var rate = Math.pow(base,1.5);
		var rateR = Math.pow(1 - x, 2);
		var progress = -Math.abs(Math.cos(rate * (2.5 * Math.PI) )) + 1;
		return (1- rateR) + (progress * rateR);
	}
		can = new Vivus('can-horizontal', {type: 'OneByOne', duration: 150});
```

Hope you can help me!
Thanks again! :)

**Comment by maxwellito** [comment]
Hi there,
First, thanks for these kind words :) It's sweet to start an issue with this message.

About your problem. I kept thinking about a hack since this morning and there's no magic solution. I have different ones:

1. Find a way on your SVG editor to ask him to export the path points in the reverse order. Like `<path d="4-3-2-1"/>` to `<path d="1-2-3-4"/>`. But I have no idea how to do that, even manually :-/ *(I tried but I gave up)*.
2. Have a custom version of Vivus which allow you to go use negative values in animation timing function.

In `vivus.js` line 635. Change

```js
`progress = this.pathTimingFunction(Math.max(0, Math.min(1, progress)));`
```

to 

```
progress = this.pathTimingFunction(progress);
```
Then you will be able to use `function (x) {return -x}` as `animTimingFunction`.
Check the result on http://maxwellito.github.io/drafts/vivus-issue-66/ (and the [code](https://github.com/maxwellito/drafts/tree/gh-pages/vivus-issue-66))

**Bottom note**
I find it curious that your SVG editor exported your path with the points defined in the opposite order of your drawing. Which software do you use?

**Comment by smitterko** [comment]
I had the same problem! I had an SVG where one of the lines was drawing in the correct direction but the other two weren't. I figured it had to be something defined in the SVG file somehow when I exported from Illustrator. 

It turns out at least in Illustrator 2024, there's an option to reverse path direction.

Select the path with the regular Selection tool. Then Object menu > Path > Reverse Path Direction. Worked like a charm!! 
<img width="675" alt="Screenshot 2023-12-13 at 3 52 56 PM" src="https://github.com/maxwellito/vivus/assets/4835936/a8dace59-dc2f-41e1-a24f-df3452cb401a">

Thank you for this awesome library!
