### ISSUE TITLE
to change the duration from frames to seconds!

### ISSUE THREAD

**Issue by Melaga** [maxwellito/vivus#72]
Hi Maxwellito!
Is that easy to change draw function's duration to seconds?!

**Comment by maxwellito** [comment]
Hi there,

I'm sorry this won't be possible because Vivus is using `requestAnimationFrame` which allow smooth animation and avoid frame drop. So depending on the client machine it can be very fast of very slow. There's not way to calculate it. You can keep in mind an average score of 30 frames per second and adapt your instance with it.

Sorry about that.
