### ISSUE TITLE
Adding dynamic color

### ISSUE THREAD

**Issue by crispouille** [maxwellito/vivus#76]
Hey @maxwellito ,

I saw on your site that u could change dynamicaly the color of the SVG which inherit from the parents bloc. Any advice to do it, I don't get how doing it ?

Thanks for your module and everything !

**Comment by maxwellito** [comment]
Hi there,

So, on the demo page, the trick I use to inherit the same color as the color test is due to the variable `currentColor` (see [CSS Tricks](https://css-tricks.com/currentcolor/) for more info).
In CSS, if you use the value `currentColor` (for `background-color` or `border-color`) it will use the text color of the current context. That's what I'm using for the `stroke` property on my SVG *(in the demo page the SVG are inline, so I can CSS to style them)*.

For example:
```html
<div class="head">
  <svg>
    <path d="...."/>
  </svg>
</div>
```

```css
.head {
  color: red;
}
path {
  stroke: currentColor;
}
```

In this example, all `path` element will get the color of their context. So the only path element would be red.

**Comment by crispouille** [comment]
Thanks mate ! Sounds wonderful, I'm going to look at it !

**Comment by joannesalfa** [comment]
It didnt help me because I need to use selector at svg path to add a class in following this markup:

![Image of Yaktocat](https://i.imgur.com/gA0wR2E.png)

I don't know about #document, is that another iframe?
