### ISSUE TITLE
Why are you adding a atribute , when its not found in the attribute array ? should't it be the opposite ? 

### ISSUE THREAD

**Issue by gautamz07** [maxwellito/vivus#77]
I found the below lines of code:

Pathformer.prototype.pathMaker = function (element, pathData) {
  var i, attr, pathTag = document.createElementNS('http://www.w3.org/2000/svg','path');
  for(i = 0; i < element.attributes.length; i++) {
    attr = element.attributes[i];
    /*  DIFF :: why when not found would 
        you like to add attribute ? */
    if (this.ATTR_WATCH.indexOf(attr.name) === -1) {
      pathTag.setAttribute(attr.name, attr.value);
    }
  }

  // DIFF :: I am not understanding whats happening below.
  for(i in pathData) {
    pathTag.setAttribute(i, pathData[i]);
  }
  return pathTag;
};

Line 223 HERE https://github.com/maxwellito/vivus/blob/master/dist/vivus.js#L223.

Now the condition you have given is 

 if (this.ATTR_WATCH.indexOf(attr.name) === -1) {
      pathTag.setAttribute(attr.name, attr.value);
    }

The above i believ reads , "when the attribute is not found in the attribute array , add its attibute name and value to pathTag" , should't it be the opposite way around ? 

I am new to SVG , did't mean to bug you with a new issue , just really wanted to ask this question. 

Thank you for your time.

**Comment by maxwellito** [comment]
Hi there,
Sorry for the delay. It took me a bit of time to remember what this piece of code what doing :-D

The `Pathformer` class is here to transform shape tags (like `circle`, `rect`, `line`...) to `path` tags. These shape tags got attributes to define their points (like `x1`, `x2`, `c`....). But if these attributes are using percentage instead of pixel values, it's impossible to transform the the shape tag to a `path` tag (SVG problem).

> ### "But it's like that, and that's the way it is!"

*RUN DMC*

So when the Pathformer transform a shape tag, it will clone all attributes which have no link with points (these can be custom attributes) and for the others it will check they doesn't contain percentage values (or will trigger an error).

**Example**

Pathformer would transform this shape tag 

```html
<line x1="68" y1="68" x2="131" y2="131" id="myLine"></line>
```

into 

```html
<path d="M68,68L131,131" id="myLine"></path>
```

**Comment by gautamz07** [comment]
@maxwellito Thank you Sir and sorry for the delayed response ! Thanks a lot for taking the time to explain that to me . 

Cheers.
