### ISSUE TITLE
IE8 svg object constructor 

### ISSUE THREAD

**Issue by blinkcat** [maxwellito/vivus#81]
Hi,
In IE8 , the constructor of  svg object is  [object HTMLGenericElement] . Maybe, you should judge svg with nodeName instead of constructor。

**Comment by maxwellito** [comment]
Hi there,
Well, I never considered to work on IE8 because [SVG is not supported](http://caniuse.com/#feat=svg) and this browser is [no longer supported by Microsoft](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support). Plus, I don't think I can use required methods like `getTotalLength()` on `path` elements. So I prefer to focus on bugs and new features.
Sorry
